version: '3.8'

services:
  movies-webapp:
    image: movies-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - WWW_ROOT_PATH=./wwwRoot
      - DATABASE_PATH=./database
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
