version: '3.8'

services:
  movies-webapp:
    image: movies-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - WWW_ROOT_URI=./wwwRoot
      - DATABASE_PATH=./database
