version: "3.7"

services:
    movies-api:
      build: 
        context: .
        dockerfile: DockerFile
      ports:
        - "5001:5001"
      volumes:
        - ../:/app
      environment:
        - TZ=UTC
        - WWW_ROOT_URI=../Movies.Client
        - DATABASE_PATH=../Movies.DataAccess/Database
      tty: true
